I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 66, in script
    $ roll = StatCheck.Stat_check(Agility)
  File "game/script.rpy", line 66, in <module>
    $ roll = StatCheck.Stat_check(Agility)
AttributeError: 'NoneType' object has no attribute 'Stat_check'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 66, in script
    $ roll = StatCheck.Stat_check(Agility)
  File "/home/unkown/Renpy/renpy/ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/unkown/Renpy/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 66, in <module>
    $ roll = StatCheck.Stat_check(Agility)
AttributeError: 'NoneType' object has no attribute 'Stat_check'

Linux-6.5.0-28-generic-x86_64-with-glibc2.38 x86_64
Ren'Py 8.2.2.24042401+nightly
Furventure 1.1.1
Fri Apr 26 23:17:10 2024
